#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    defaults:
#      path: /api
#      permanent: true
authentication_token:
  path: /authentication_token
  methods: ['POST']